### ISSUE TITLE
1.13.1

### ISSUE THREAD

**Issue by Straikerinos** [Nicc0/Sky-Wars#24]
commands now working !
if i send command /sw info it say me "Wrong Arguments! Use /skywars too see a list of commands."
tihs same at commands: /sw tool, /sw setroom [room].
and if i start server i say to console SkyWars01 [my map] canť locate lobby.. but i have set lobby. please help.

**Comment by EndePlay** [comment]
> Команды сейчас работают! 
> если я посылаю команду / sw info, она говорит мне: «Неправильные аргументы! Используйте / skywars, чтобы увидеть список команд». 
> То же самое в командах: / sw tool, / sw setroom [room]. 
> и если я запускаю сервер, я говорю консоли SkyWars01 [моя карта] не может найти лобби ... но я установил лобби. пожалуйста помоги.

Commands / sw tool, / sw setroom removed in new updates

**Comment by marcusmauricio** [comment]
Hello,
As for the lobby,
Do /sw lobby create wherever you would like to set the lobby's spawn.
