### ISSUE TITLE
Server crash after /sw addspawn!

### ISSUE THREAD

**Issue by WahyuAgung27** [Nicc0/Sky-Wars#4]
Hey, I'd like to report error in my server.
This is console say when want to add /sw addspawn (ArenaName):
After this message, my server goes Crash & down

16.02 06:56:41 [Server] ERROR The server has stopped responding! 16.02 06:56:41 [Server] ERROR Please report this to http://www.spigotmc.org/ 16.02 06:56:41 [Server] ERROR Be sure to include ALL relevant console errors and Minecraft crash reports 16.02 06:56:41 [Server] ERROR Spigot version: git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) 16.02 06:56:41 [Server] ERROR ------------------------------ 16.02 06:56:41 [Server] ERROR Server thread dump (Look for plugins here before reporting to Spigot!): 16.02 06:56:41 [Server] ERROR ------------------------------ 16.02 06:56:41 [Server] ERROR Current Thread: Server thread 16.02 06:56:41 [Server] ERROR PID: 16 | Suspended: false | Native: false | State: RUNNABLE 16.02 06:56:41 [Server] ERROR Stack: 16.02 06:56:41 [Server] ERROR it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.get(Long2ObjectOpenHashMap.java:379) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkIfLoaded(ChunkProviderServer.java:111) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:124) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.World.getChunkAt(World.java:329) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.World.getChunkAtWorldCoords(World.java:325) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.World.getType(World.java:806) 16.02 06:56:41 [Server] ERROR org.bukkit.craftbukkit.v1_11_R1.block.CraftBlock.setData(CraftBlock.java:104) 16.02 06:56:41 [Server] ERROR org.bukkit.craftbukkit.v1_11_R1.block.CraftBlock.setData(CraftBlock.java:90) 16.02 06:56:41 [Server] ERROR org.skywars.f.a.E(Game.java:1052) 16.02 06:56:41 [Server] ERROR org.skywars.d.a.a.a(ArenaAddSpawnCommand.java:48) 16.02 06:56:41 [Server] ERROR org.skywars.d.b.onCommand(CommandArena.java:64) 16.02 06:56:41 [Server] ERROR org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) 16.02 06:56:41 [Server] ERROR org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) 16.02 06:56:41 [Server] ERROR org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) 16.02 06:56:41 [Server] ERROR java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 16.02 06:56:41 [Server] ERROR java.util.concurrent.FutureTask.run(FutureTask.java:266) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) 16.02 06:56:41 [Server] ERROR net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) 16.02 06:56:41 [Server] ERROR java.lang.Thread.run(Thread.java:748) 16.02 06:56:41 [Server] ERROR ------------------------------ 16.02 06:56:41 [Server] ERROR Entire Thread Dump: 16.02 06:56:41 [Server] ERROR ------------------------------ 16.02 06:56:41 [Server] ERROR Current Thread: Netty Epoll Server IO #3 16.02 06:56:41 [Server] ERROR PID: 28 | Suspended: false | Native: true | State: RUNNABLE 16.02 06:56:41 [Server] ERROR Stack: 16.02 06:56:41 [Server] ERROR io.netty.channel.epoll.Native.epollWait(Native Method) 16.02 06:56:41 [Server] ERROR io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194) 16.02 06:56:41 [Server] ERROR io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219) 16.02 06:56:41 [Server] ERROR io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) 16.02 06:56:41 [Server] ERROR java.lang.Thread.run(Thread.java:748) 16.02 06:56:41 [Server] ERROR ------------------------------ 16.02 06:56:41 [Server] ERROR Current Thread: pool-12-thread-1 16.02 06:56:41 [Server] ERROR PID: 88 | Suspended: false | Native: false | State: WAITING 16.02 06:56:41 [Server] ERROR Stack: 16.02 06:56:41 [Server] ERROR sun.misc.Unsafe.park(Native Method) 16.02 06:56:41 [Server] ERROR java.util.concurrent.locks.LockSupport.park(LockSupport.java:175) 16.02 06:56:41 [Server] ERROR java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039) 16.02 06:56:41 [Server] ERROR java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442) 16.02 06:56:41 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067) 16.02 06:56:41 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)

**Comment by cheekeh** [comment]
I get this error to! I don't know why but even when I do /sw tool wand Test1 it doesn't work. 
I've messaged Nic0 but still no response. Looks like a good plugin but it's a shame that it's not working.

**Comment by cheekeh** [comment]
I've fixed the /sw tool wand thing but still, the spawn crashes the server.
