### ISSUE TITLE
LeakSkyWars bugs

### ISSUE THREAD

**Issue by cheekeh** [Nicc0/Sky-Wars#5]
Hello,

So I set up a game on my server and I found a few bugs .
When a player joins the server, it gives out this error: https://hastebin.com/qohegidobo.vbs

Also, when I join a game I can move items in my inventory, also, when I click the bed, I get kicked from my skywars server and back to the hub. I don't want that to happen. I don't know if its because there is a main lobby that I've not set or something.

I have also found an error with chests. When I set an ultra chest it says but then when I join a game there is nothing in that chest.

Also, when I jump of the edge with my alt and then I try to join the game once it's ended, I just get kicked straight back to my hub. Then when I try to join with my main account, I get kicked but for some reason, It says I joined the game when I didn't. It says 'Start cancelled. Not enough players.' on the scoreboard it says 2/2 .

I don't get it. No error. I have a bungeecord server. The server version is 1.12.2.
I have 2GB of ram.

edit; also, when i join the game for a second time. (second time playing the map) it goes through with the glitch above then when it starts eventually.. the cages don't spawn. I also have another error. https://hastebin.com/bobudajuya.vbs

Hope you can get this fixed.
cheeky ;)

another error: https://hastebin.com/uzesilorab.vbs .
thats when I retry to join a game. the second game. after a restart it works fine ..... and then the error happens again..

**Comment by Nicc0** [comment]
[https://img.shields.io/badge/Status-%20Opened-red.svg?style=flat-square](url)

**Comment by Nicc0** [comment]
_**# Opened**_

**Comment by Nicc0** [comment]
_**# Closed**_
