### ISSUE TITLE
Cages, Chests Issue

### ISSUE THREAD

**Issue by Redblock6YT** [Nicc0/Sky-Wars#6]
Hello Nicc0!
Im Redblock6 from spigot! Anyway, When i made the arena i played it the first time for the other person the chests just broke on their island then, the 2nd time the cadges were gone! And after a few secs there was a whole where we were standing(Not small huge) and we fell and died. Please fix! - Redblock6

**Comment by cheekeh** [comment]
Same issue that I’ve got. But for some reason I get kicked when I try to join a second game.
